### ISSUE TITLE
Training curves

### ISSUE THREAD

**Issue by fdeng18** [tung-nd/TPC-tensorflow#1]
Hi @tung-nd,

Thanks for the great work and for releasing the code. Would you be able to share the training curves (e.g., in .json files) of TPC, DBC, CVRL, and CURL on standard and natural background DMC? That would be very helpful for follow-up work to reproduce the figures in your paper.

Best,
Fei

**Comment by noobitard** [comment]
Hi @fdeng18, sorry for the late reply. 
Here is our full logdir: https://drive.google.com/file/d/1JeB2CZLh2qmSiRJjKuYZK5UANAn0--6x/view?usp=sharing
