### ISSUE TITLE
DBC Implementation

### ISSUE THREAD

**Issue by vedantdave97** [tung-nd/TPC-tensorflow#2]
Hello @tung-nd,
Thanks for the code and training curves.

I was implementing DBC and as mentioned in your paper, I used multiple distracting scenes in training and testing. 
I used your dataset and I changed the "-`-total frames`" to 30000 instead of 1000, just to get more frames in training and testing. 
I also added `self._bg_source.reset()` here: (https://github.com/facebookresearch/deep_bisim4control/blob/main/dmc2gym/wrappers.py#L188) just to reset the bg initialization of every episode (Correct me if I am wrong).
I also implemented the same parameters as mentioned in the DBC paper at page no.16.

I got these results for Cheetah Run task (Its currently under training and yet to reach 1M):
![Screenshot from 2023-05-31 19-53-25](https://github.com/VinAIResearch/TPC-tensorflow/assets/83164901/3d47b500-63dd-4e93-a5dc-b4339ae98a61)

These results are very different from what is mentioned in the paper. It will be really helpful if you can point out my implementation mistake or tell me what you exactly changed in the DBC code.

**Comment by noobitard** [comment]
Hi @VedantDave1997,

Sorry for the late reply. For DBC, unfortunately we currently do not have the code anymore. As I remember, we used their official implementation and did not change anything other from the dataset.

**Comment by vedantdave97** [comment]
Hello @noobitard,
Thank you for the response. I understand that the code is no longer available. I'll mention the results that I have obtained in my work.
